name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit Linux
          - os: ubuntu-22.04
            python: 37
            platform: manylinux_x86_64
          - os: ubuntu-22.04
            python: 38
            platform: manylinux_x86_64
          - os: ubuntu-22.04
            python: 39
            platform: manylinux_x86_64
          - os: ubuntu-22.04
            python: 310
            platform: manylinux_x86_64
          - os: ubuntu-22.04
            python: 311
            platform: manylinux_x86_64

          # 64-bit macOS
          - os: macos-12
            python: 37
            platform: macosx_x86_64
          - os: macos-12
            python: 38
            platform: macosx_x86_64
          - os: macos-12
            python: 39
            platform: macosx_x86_64
          - os: macos-12
            python: 310
            platform: macosx_x86_64
          - os: macos-12
            python: 311
            platform: macosx_x86_64

          # 64-bit Windows
          - os: windows-2019
            python: 37
            platform: win_amd64
          - os: windows-2019
            python: 38
            platform: win_amd64
          - os: windows-2019
            python: 39
            platform: win_amd64
          - os: windows-2019
            python: 310
            platform: win_amd64
          - os: windows-2019
            python: 311
            platform: win_amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rtools on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          # rtools contains mingw-w64
          choco install rtools --no-progress
          echo 'c:\rtools40\ucrt64\bin;' >> $env:GITHUB_PATH

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform }}
          CIBW_BUILD_VERBOSITY: 3

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

